// Adds (or refreshes) the News rows for the Displacement Report, so the report
// appears on the homepage and /news as "NextChapter Report" cards that link to
// the report's own page in the same tab.
//
// Idempotent: keyed on newsSlug (which is @unique), so re-running updates each
// row rather than creating duplicates. Ids are generated by Prisma's
// @default(cuid()), the same way the app's own create() calls do.
//
// Run: npm run report:news
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const SITE = 'https://launchyournextchapter.com'
const SLUG = 'displacement-report-september-2026'
const URL = `${SITE}/reports/${SLUG}`
const OG = `${SITE}/reports/displacement-report-2026-09-og.png?v=1.72`

// Tags are mapped to the site's fixed tag vocabulary (src/lib/news/tags.ts):
// 'news' and 'data_research' stand in for the report's "reports"/"data" topics,
// which are not keys in that list.
const NEWS_TAGS = ['news', 'data_research']

const base = {
  url: URL,
  ingestionSource: 'manual',
  status: 'reviewed',
  newsKind: 'report',
  newsSource: 'NextChapter Research',
  newsTags: NEWS_TAGS,
  newsImageUrl: OG,
}

const items = [
  {
    ...base,
    newsSlug: SLUG,
    title: 'Fewer layoffs, longer searches: the September 2026 white-collar displacement report',
    newsTitle: 'Fewer layoffs, longer searches: the September 2026 white-collar displacement report',
    newsPublishedAt: new Date('2026-10-05T12:00:00Z'),
    newsBlurb:
      'Monthly white-collar report: the White-Collar Long-Term Unemployment Index at 162, 27.1% of the unemployed out 27+ weeks, AI attribution in SEC filings, plus skills, states and policy.',
  },
  {
    ...base,
    // Distinct slug so the correction is its own card; both link to the report.
    newsSlug: 'displacement-report-september-2026-v1-2-correction',
    title: 'Correction and Q3 addendum: NextChapter Displacement Report v1.2',
    newsTitle: 'Correction and Q3 addendum: NextChapter Displacement Report v1.2',
    newsPublishedAt: new Date('2026-10-06T12:00:00Z'),
    newsBlurb:
      'Version 1.2 corrects the SEC AI-attribution count (16 of 170 restructuring filings, up from 2), renames the index to the White-Collar Long-Term Unemployment Index, and adds a Q3 2026 quarterly addendum.',
  },
  {
    ...base,
    newsSlug: 'displacement-report-september-2026-v1-6',
    title: 'Displacement Report v1.6: immigration, college AI programs, retraining and a correction',
    newsTitle: 'Displacement Report v1.6: immigration, college AI programs, retraining and a correction',
    newsPublishedAt: new Date('2026-10-06T20:00:00Z'),
    newsBlurb:
      "Version 1.6 finds the rise in long job searches is among U.S.-born professionals, not explained by immigration, and corrects our reading of older workers' participation. It also adds career-ladder and training data, AI programs at colleges by career stage, WIOA retraining results and a monthly AI use-case watch.",
  },
  {
    ...base,
    newsSlug: 'displacement-report-september-2026-v1-72',
    title: 'Displacement Report v1.72: AI exposure by occupation, degree holders, student debt and productivity',
    newsTitle: 'Displacement Report v1.72: AI exposure by occupation, degree holders, student debt and productivity',
    newsPublishedAt: new Date('2026-10-07T20:00:00Z'),
    newsBlurb:
      "The report finds the rise in long job searches is among U.S.-born professionals, not explained by immigration, and corrects our reading of older workers' participation. Version 1.7 adds a check for displacement hidden inside jobs (none found so far), a feature on why AI capability is outrunning organizational change, and a standing change-record policy. Version 1.71 tests AI exposure against outcomes across occupations, tracks bachelor's and master's holders by experience, and adds college costs and student debt. Version 1.72 adds a total factor productivity analysis: no sign of AI in underlying productivity yet. It also includes career-ladder and training data, AI programs at colleges by career stage, WIOA retraining results and a monthly AI use-case watch.",
  },
]

async function main() {
  for (const data of items) {
    const row = await prisma.researchLibraryItem.upsert({
      where: { newsSlug: data.newsSlug },
      update: data,
      create: data,
    })
    console.log(`News row ready: ${row.id} → ${data.newsTitle}`)
  }
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
