// Adds (or refreshes) the News row for the latest Displacement Report edition,
// so the report appears on the homepage and /news as a "NextChapter Report"
// card that links to the report's own page in the same tab.
//
// Idempotent: keyed on newsSlug (which is @unique), so re-running updates the
// row rather than creating a duplicate. The id is generated by Prisma's
// @default(cuid()), the same way the app's own create() calls do.
//
// Run: npm run report:news
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const SITE = 'https://launchyournextchapter.com'
const SLUG = 'displacement-report-september-2026'

// Tags are mapped to the site's fixed tag vocabulary (src/lib/news/tags.ts):
// 'news' and 'data_research' stand in for the report's "reports"/"data" topics,
// which are not keys in that list.
const NEWS_TAGS = ['news', 'data_research']

async function main() {
  const data = {
    url: `${SITE}/reports/${SLUG}`,
    ingestionSource: 'manual',
    title: 'Fewer layoffs, longer searches: the September 2026 white-collar displacement report',
    status: 'reviewed',
    newsKind: 'report',
    newsSource: 'NextChapter Research',
    newsPublishedAt: new Date('2026-10-05T12:00:00Z'),
    newsTags: NEWS_TAGS,
    newsTitle: 'Fewer layoffs, longer searches: the September 2026 white-collar displacement report',
    newsBlurb:
      'Monthly white-collar displacement report: 27.1% of the unemployed out 27+ weeks, AI cited in 21% of 2026 layoffs vs ~5% of SEC filings, senior openings down 20%, plus WIOA, benefits and age trends.',
    newsImageUrl: `${SITE}/reports/displacement-report-2026-09-og.png`,
    newsSlug: SLUG,
  }

  const row = await prisma.researchLibraryItem.upsert({
    where: { newsSlug: SLUG },
    update: data,
    create: data,
  })
  console.log(`News row ready: ${row.id} → ${data.url}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
