// GENERATED by ~/nextchapter-jobs/export-taxonomy.py from ncrawl/taxonomy.py.
// Do not edit by hand — change the Python and re-run the export.

const re = (source: string) => new RegExp(source, 'i')

export const NEGATIVE = re("\\b(executive assistant|assistant to the|executive administrator|administrative (assistant|coordinator)|director of photography|art director|creative director assistant|funeral director|athletic director assistant|vice president of sales development representative|deputy assistant|junior (vice president|director|principal)|director,? (of )?(nursing )?assistant|student (worker|assistant|employee|intern|ambassador|aide)|intern(ship)?|apprentice|trainee|executive chef|sous chef|chef de)\\b")
export const REPORTING_REF = re("\\s*[,\\-\u2013\u2014]?\\s*\\b(to|for|reporting to|reports to|supporting|support to|in the office of|office of)\\s+(the\\s+)?(ceo|cfo|coo|cto|cmo|cio|ciso|chro|cro|cpo|clo|chief\\s+[a-z ]{2,25}officer|president|chairman|chairwoman|chair|founder|board|managing partner|gm|general manager)\\b.*$")
export const BOARD = re("\\b(board\\s+(member|director|seat|chair|trustee|of\\s+directors|of\\s+trustees|of\\s+governors|appointment|opportunit)|non[- ]?executive director|\\bned\\b|trustee|advisory board|advisory council|committee chair|independent director|(audit|risk|compensation|nominating|governance)\\s+committee)\\b")
export const JUNIOR = re("\\b(intern(ship)?s?\\b|co[- ]?op\\b|trainee|apprentice|graduate (program|scheme|analyst|engineer)|new grad|entry[- ]level|early career|campus hire|rotational (program|analyst)|(junior|jr\\.?|assistant|associate|entry)\\s+(analyst|associate|engineer|developer|designer|manager|accountant|consultant|specialist|coordinator|administrator|representative|buyer|planner|recruiter)|(analyst|associate|coordinator|specialist|representative|administrator|assistant|clerk|technician|apprentice|scheduler|dispatcher|receptionist|bookkeeper|teller|cashier|server|driver|operator|attendant)\\s*(i|ii|1|2)?$|^(analyst|associate|coordinator|specialist|representative|administrator)\\b)")
export const JUNIOR_EXEMPT = re("\\b(assistant\\s+(dean|provost|superintendent)|(associate|deputy)\\s+(general counsel|chief|dean|provost|vice chancellor|chancellor|superintendent|partner|head of school|athletic director|medical director|commissioner))\\b")
export const FRONTLINE = re("\\b((assistant |associate |co-?)?store (manager|director|lead)|(restaurant|store|location|unit|club|dealership|franchise) general manager|(assistant|shift|restaurant|kitchen|floor|department|branch office|front desk|front of house|back of house|night|overnight|crew|bar|banquet|catering|retail|location) (manager|supervisor|lead)|shift (lead|leader)|team member|crew member|(truck |delivery |cdl |rideshare )?driver|courier|warehouse (associate|worker|operator)|forklift|picker|packer|material handler|loader|laborer|cashier|barista|bartender|server|host(ess)?|line cook|cook|dishwasher|housekeep(er|ing)|custodian|janitor|groundskeeper|landscaper|security (officer|guard)|caregiver|home health aide|(certified )?nurs(e|ing) (aide|assistant)|\\bcna\\b|medical assistant|phlebotomist|pharmacy technician|patient care technician|sales associate|retail associate|merchandiser|stocker|customer service representative|call center|teller|(maintenance|hvac|field service|automotive|diesel|aviation) (technician|mechanic)|mechanic|electrician|plumber|welder|machinist|carpenter|painter|assembler|production (worker|associate|operator)|machine operator|equipment operator|installer|(dental|veterinary) (assistant|technician)|receptionist|(substitute|teacher'?s?) (teacher|aide)|paraprofessional)\\b")
export const UNDER_DIRECTOR = re("\\b(associate|assistant) (director|vice president)\\b|\\bavp\\b")
export const PARTNER_EXCLUDE = re("\\b((business|hr|human resources|people|finance|financial|talent|it|technology|data|marketing|comms?|communications|legal|payroll|operations)\\s+partner|\\bhrbp\\b|business partnering|partner\\s+(manager|management|marketing|success|support|operations|development|enablement|engineer|engineering|solutions?|account|experience|program|programme|services|onboarding|integration|analyst|specialist|coordinator|associate|relations|strategy)|(channel|alliance|ecosystem|referral|reseller|agency|implementation|delivery|solution|technology|integration|strategic|global|regional)\\s+partner(?!s?hip\\s+(director|vice))|partnerships?\\s+(manager|lead|associate|analyst|coordinator|specialist|development|marketing|strategy)|principal\\s+(consultant|advisor|adviser|recruiter|associate|analyst|specialist|writer|designer|instructor|trainer|accountant|auditor|investigator|planner|technologist|technician|producer|editor))\\b")
export const STAFF_ENTRY = re("\\bstaff\\s+(accountant|auditor|nurse|tax (accountant|associate)|assistant|pharmacist|therapist|scientist i\\b)")
export const CSUITE_VETO = re("^(?!.*\\bchief\\b)(?!.*(?<!vice )(?<!vice-)\\bpresident\\b).*\\b((?<!general )manager|engineer|analyst|specialist|coordinator|consultant|architect|representative|associate|recruiter|designer|developer|scientist)\\b")
export const REPORTING_REF_GLOBAL = new RegExp(REPORTING_REF.source, 'gi')

export type RungName =
  | "BOARD"
  | "CHIEF_OF_STAFF"
  | "C_SUITE"
  | "DIRECTOR"
  | "EVP_SVP"
  | "HEAD"
  | "MANAGER"
  | "OTHER"
  | "PARTNER"
  | "PRINCIPAL"
  | "SCHOOL_LEADER"
  | "SENIOR_IC"
  | "SR_MANAGER"
  | "VP"

export const LADDER: { name: RungName; rank: number; pattern: RegExp }[] = [
  { name: "C_SUITE", rank: 100, pattern: re("\\b(chief [a-z ]{2,30}officer|c[eftimopr]o\\b|cxo\\b|chro\\b|ciso\\b|cdo\\b|clo\\b|caio\\b|(?<!vice )(?<!vice-)(?<!v\\.)(group |global |deputy )?president\\b|(?<!account )executive director|managing partner|general manager|(?<!associate )(?<!deputy )general counsel|chief counsel|(?<!associate )(?<!assistant )(?<!deputy )(?<!vice )(?<!vice-)(chancellor|provost|superintendent|dean)\\b|head of school|executive vice chancellor)\\b") },
  { name: "DIRECTOR", rank: 68, pattern: re("\\b(associate|assistant|deputy)\\s+(general counsel|dean|provost|superintendent)\\b") },
  { name: "SCHOOL_LEADER", rank: 68, pattern: re("\\b((elementary|middle|high|upper|lower|primary|secondary|charter|school)\\s+school\\s+principal|(school|building|campus)\\s+principal|principal\\s*[,\\-\u2013\u2014]?\\s*[A-Z][\\w'.]*\\s+(high|middle|elementary|primary|secondary|academy|school|charter)|principal\\s+of\\s+[A-Z])") },
  { name: "CHIEF_OF_STAFF", rank: 68, pattern: re("\\bchief of staff\\b") },
  { name: "EVP_SVP", rank: 90, pattern: re("\\b(executive vice president|senior vice president|e\\.?v\\.?p\\.?|s\\.?v\\.?p\\.?|group vice president|senior managing director)\\b") },
  { name: "VP", rank: 80, pattern: re("\\b(vice president|v\\.?p\\.?|vice[- ]chancellor)\\b") },
  { name: "HEAD", rank: 72, pattern: re("\\b(head of|global head|group head)\\b") },
  { name: "DIRECTOR", rank: 65, pattern: re("\\b(senior director|sr\\.? director|executive director|managing director|director)\\b") },
  { name: "SR_MANAGER", rank: 52, pattern: re("\\bprincipal\\s+(engineer|scientist|architect|consultant|designer|researcher|analyst|developer|product manager|program manager|software|data|member of technical staff)\\b") },
  { name: "PARTNER", rank: 78, pattern: re("^(senior |sr\\.? |equity |salaried |non-equity )?partner\\b(?!\\s+(sales|marketing|manager|management|success|engineer|solutions?|development|program|operations|enablement|account|relations))|\\b(managing|general|founding|operating|venture|investment|equity|deal|audit|tax|assurance|advisory|consulting|law firm|practice|client service)\\s+partner\\b") },
  { name: "PRINCIPAL", rank: 70, pattern: re("\\bprincipal\\b") },
  { name: "SR_MANAGER", rank: 50, pattern: re("\\b(senior manager|sr\\.? manager|group manager|senior principal|distinguished|staff engineer|principal engineer|senior lead)\\b") },
]

export const LOWER_LADDER: { name: RungName; rank: number; pattern: RegExp }[] = [
  { name: "SENIOR_IC", rank: 45, pattern: re("\\b(staff|principal|distinguished|senior staff|lead|senior|sr\\.?)\\s+([a-z&/+-]+\\s+){0,3}(engineer|scientist|architect|developer|analyst|designer|researcher|consultant|economist|actuary|accountant|auditor|counsel|attorney|lawyer|strategist|product manager|program manager|project manager|product owner|technologist|underwriter|statistician|writer|editor|advisor|adviser|specialist|account executive|recruiter|business partner|partner|controller|planner)\\b|\\b(product|business|marketing|design|engineering|program|programme|operations|ops|finance|legal|people|sales|partnerships?|growth|strategy|data|research|analytics|content|brand|community|policy|security|compliance|practice|engagement|delivery|project|implementation|solutions|go-to-market|gtm|revenue|ux|creative)\\s+lead\\b|\\b(member of technical staff|tech lead|technical lead|enterprise account executive|strategic account executive|solutions architect|forward deployed engineer)\\b") },
  { name: "MANAGER", rank: 40, pattern: re("\\b(manager|team lead(er)?|group lead(er)?|supervisor of|practice lead|engagement lead|controller|counsel)\\b") },
]

export const RUNG_VETO: Partial<Record<RungName, RegExp>> = { PARTNER: PARTNER_EXCLUDE, PRINCIPAL: PARTNER_EXCLUDE, C_SUITE: CSUITE_VETO }
export const MANAGER_FLOOR = 40
